spark-master:
  image: earthquakesan/hadoop-spark-master
  hostname: spark-master
  container_name: spark-master
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
  env_file:
    - ./hadoop.env
  ports:
      - "8080:8080"

spark-worker:
  image: earthquakesan/hadoop-spark-worker
  hostname: spark-worker
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
    - SPARK_MASTER_URL=spark://spark-master:7077
  env_file:
    - ./hadoop.env

spark-notebook:
  image: earthquakesan/hadoop-spark-notebook
  hostname: sparknotebook
  container_name: sparknotebook
  domainname: hadoop
  net: hadoop
  environment:
    - SPARK_NOTEBOOK_MASTER=yarn-client
  env_file:
    - ./hadoop.env
  ports:
    - "9000:9000"
